[build-system]
requires = ["uv_build>=0.11.3,<0.12.0"]
build-backend = "uv_build"

[project]
name = "echolabel"
version = "0.1.0"
description = "Interactive echogram labelling tools"
readme = "README.md"
authors = [{name = "Gaspard Ringuenet", email = "gaspard.ringuenet@proton.me"}]
requires-python = ">=3.12"
dependencies = [
    # io
    "xarray>=2025.6.1,<2026",
    "netcdf4>=1.7.3,<2",
    "zarr>=2.18.7,<3",
    "dask>=2026.3.0,<2026.4.0",
    "echoregions>=0.2.3", # not pinned: compatibility with echoregions is a major objective
    # data wrangling
    "numpy>=1.26.4,<2",
    "pandas>=2.3.3,<3",
    # images generation
    "matplotlib>=3.10.8,<4",
    "Pillow>=12.0.0,<13",
    # gui
    "labelme==6.0.0", # pinned: any change in JSON files management would break echolabel
    # cli
    "click>=8.3.2,<9",
    "tqdm>=4.68.0,<5",
    # cache management
    "platformdirs>=4.9.4,<5",
]

[dependency-groups]
# downloading data for demo mode
demo = ["requests>=2.34.0,<3"]

# developper mode
dev = [
  {include-group = "lint"},
  {include-group = "test"}
]
lint = [
  "ruff"
]
test = [
    "pytest>=9.0.2",
    "pytest-cov>=7.1.0",
]
# documentation building
docs = [
    "furo>=2025.12.19",
    "myst-parser>=5.1.0",
    "sphinx>=9.0.4",
]

[project.scripts]
echolabel = "echolabel.cli:cli"

[tool.ruff]
line-length = 120
